from __future__ import annotations

from typing import Protocol

from piper_on_bunker.models import Pose, SkillResult


class ArmAdapter(Protocol):
    def get_state(self) -> dict: ...
    def move_to_named_pose(self, name: str) -> SkillResult: ...
    def move_to_pose(self, pose: Pose) -> SkillResult: ...
    def press(self, pose: Pose, depth_m: float) -> SkillResult: ...
    def retract(self) -> SkillResult: ...
    def stop(self) -> SkillResult: ...
