from typing import Protocol


class BunkerInterface(Protocol):
    def lock_base(self) -> bool: ...
    def unlock_base(self) -> bool: ...
    def is_base_stopped(self) -> bool: ...
    def request_navigation_pause(self) -> bool: ...
    def navigation_ready(self) -> bool: ...
    def get_navigation_direction(self) -> str: ...
